name: taboo_word_maze
description: A new Flutter project.
# The following line prevents the package from being accidentally published to
# pub.dev using `flutter pub publish`. This is preferred for private packages.
publish_to: 'none' # Remove this line if you wish to publish to pub.dev

# The following defines the version and build number for your application.
# A version number is three numbers separated by dots, like 1.2.43
# followed by an optional build number separated by a +.
# Both the version and the builder number may be overridden in flutter
# build by specifying --build-name and --build-number, respectively.
# In Android, build-name is used as versionName while build-number used as versionCode.
# Read more about Android versioning at https://developer.android.com/studio/publish/versioning
# In iOS, build-name is used as CFBundleShortVersionString while build-number is used as CFBundleVersion.
# Read more about iOS versioning at
# https://developer.apple.com/library/archive/documentation/General/Reference/InfoPlistKeyReference/Articles/CoreFoundationKeys.html
# In Windows, build-name is used as the major, minor, and patch parts
# of the product and file versions while build-number is used as the build suffix.
version: 1.0.0+1

environment:
  sdk: '>=2.19.0 <3.0.0'

# Dependencies specify other packages that your package needs in order to work.
# To automatically upgrade your package dependencies to the latest versions
# consider running `flutter pub upgrade --major-versions`. Alternatively,
# dependencies can be manually updated by changing the version numbers below to
# the latest version available on pub.dev. To see which dependencies have newer
# versions available, run `flutter pub outdated`.
dependencies:
  animate_icons: ^2.0.0
  animated_text_kit: ^4.2.2
  auto_route: ^5.0.4
  auto_size_text: ^3.0.0
  bloc: ^8.1.0
  cloud_firestore: ^4.3.1
  cupertino_icons: ^1.0.5
  dartz: ^0.10.1
  device_info_plus: ^8.1.0
  dio: ^4.0.6
  dio_smart_retry: ^1.4.0
  easy_localization: ^3.0.1
  equatable: ^2.0.5
  firebase_core: ^2.4.1
  firebase_messaging: ^14.2.1
  floor: ^1.4.1
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.1
  flutter_countdown_timer: ^4.1.0
  flutter_dotenv: ^5.0.2
  flutter_local_notifications: ^13.0.0
  flutter_neumorphic: ^3.2.0
  flutter_slidable: ^2.0.0
  flutter_svg: ^2.0.0+1
  fluttertoast: ^8.1.3
  get_it: ^7.2.0
  google_fonts: ^4.0.1
  intl: ^0.17.0
  json_annotation: ^4.8.0
  json_serializable: ^6.6.0
  package_info_plus: ^3.0.2
  permission_handler: ^10.2.0
  pretty_dio_logger: ^1.2.0-beta-1
  provider: ^6.0.5
  rive: ^0.10.1
  shared_preferences: ^2.0.17
  simple_animations: ^5.0.0+3
  sizer: ^2.0.15
  sqflite: ^2.2.4+1
  timezone: ^0.9.1


dev_dependencies:
  auto_route_generator: ^5.0.3
  build_runner: ^2.3.3
  floor_generator: ^1.4.1
  flutter_lints: ^2.0.0
  flutter_test:
    sdk: flutter

# For information on the generic Dart part of this file, see the
# following page: https://dart.dev/tools/pub/pubspec

# The following section is specific to Flutter packages.
flutter:

  # The following line ensures that the Material Icons font is
  # included with your application, so that you can use the icons in
  # the material Icons class.
  uses-material-design: true

  # To add assets to your application, add an assets section, like this:
  assets:
    - .env
    - .env.development
    - assets/lang/
    - assets/animation/
    - assets/icons/

  # An image asset can refer to one or more resolution-specific "variants", see
  # https://flutter.dev/assets-and-images/#resolution-aware

  # For details regarding adding assets from package dependencies, see
  # https://flutter.dev/assets-and-images/#from-packages

  # To add custom fonts to your application, add a fonts section here,
  # in this "flutter" section. Each entry in this list should have a
  # "family" key with the font family name, and a "fonts" key with a
  # list giving the asset and other descriptors for the font. For
  # example:
  fonts:
    - family: ChakraPetch
      fonts:
        - asset: assets/fonts/Chakra_Petch/ChakraPetch-Bold.ttf
        - asset: assets/fonts/Chakra_Petch/ChakraPetch-BoldItalic.ttf
          style: italic
        
        - asset: assets/fonts/Chakra_Petch/ChakraPetch-Regular.ttf
        - asset: assets/fonts/Chakra_Petch/ChakraPetch-Italic.ttf
          style: italic

        - asset: assets/fonts/Chakra_Petch/ChakraPetch-Light.ttf
        - asset: assets/fonts/Chakra_Petch/ChakraPetch-LightItalic.ttf
          style: italic

        - asset: assets/fonts/Chakra_Petch/ChakraPetch-Medium.ttf
        - asset: assets/fonts/Chakra_Petch/ChakraPetch-MediumItalic.ttf
          style: italic

        - asset: assets/fonts/Chakra_Petch/ChakraPetch-SemiBold.ttf
        - asset: assets/fonts/Chakra_Petch/ChakraPetch-SemiBoldItalic.ttf


    - family: Marhey
      fonts:
        - asset: assets/fonts/Marhey/Marhey-Bold.ttf
        
        - asset: assets/fonts/Marhey/Marhey-Regular.ttf

        - asset: assets/fonts/Marhey/Marhey-Light.ttf

        - asset: assets/fonts/Marhey/Marhey-Medium.ttf

        - asset: assets/fonts/Marhey/Marhey-SemiBold.ttf

          
    
  
  # For details regarding fonts from package dependencies,
  # see https://flutter.dev/custom-fonts/#from-packages
